### ISSUE TITLE
String definition for length

### ISSUE THREAD

**Issue by powentonnai** [jsonx-org/java#29]
Does JSONX supports generating length attributes for String definition while converting XSD to JSON Schema.

**Comment by safris** [comment]
JSONx does not convert XSD to JSON Schema. JSONx defines its own [JSON Schema Definition (JSD) Language](https://jsonx.org/schema/) that can be represented in both XML form (`.jsdx` extension), as well JSON form (`.jsd` extension). A `example.jsdx` schema (that is expressed in XML) can be converted to a `example.jsd` schema (that is represented in JSON). Please see [ConvertTest](https://github.com/jsonx-org/java/blob/master/generator/src/test/java/org/jsonx/ConverterTest.java).
